import logging

import pytest
import yaml
from conftest import write_spec

from fanbase.cli import main
from fanbase.context import Context
from fanbase.lock import Lock, LockedSpec, dump_lock, load_lock
from fanbase.manager import all_installed, ensure, lock_context, spec_path
from fanbase.manifest import INDEX_FILENAME, dump_index, reindex
from fanbase.registry import Registry, RegistryError
from fanbase.source import is_official, moves

SHA = "ab" * 32


@pytest.fixture
def root(tmp_path, monkeypatch):
    monkeypatch.setenv("FANDANGO_PATH", str(tmp_path / "fandango"))
    return tmp_path / "fandango"


@pytest.fixture
def project(tmp_path, monkeypatch):
    """A directory to work in, as a project would be."""
    work = tmp_path / "project"
    work.mkdir()
    monkeypatch.chdir(work)
    return work


def run(capsys, *argv):
    code = main(list(argv))
    out = capsys.readouterr()
    return code, out.out, out.err


def build(root, specs, name=None):
    for (fmt, kind), meta in specs.items():
        write_spec(root, fmt, kind, f"<start> ::= '{kind}'\n", meta.pop("description", kind), **meta)
    if name:
        (root / "registry.yml").write_text(yaml.safe_dump({"name": name}))
    reg = Registry(root)
    rows, _, _ = reindex(reg)
    (root / INDEX_FILENAME).write_text(dump_index(rows, reg.info))
    return root


def republish(root, kind, text, **meta):
    """The registry changes a spec: new text, and optionally new metadata."""
    fmt = kind.split("-")[0]
    (root / "specs" / fmt / kind / f"{kind}.fan").write_text(text)
    if meta:
        path = root / "specs" / fmt / kind / "metadata.yml"
        data = yaml.safe_load(path.read_text())
        data.update(meta)
        path.write_text(yaml.safe_dump(data))
    reg = Registry(root)
    rows, _, _ = reindex(reg)
    (root / INDEX_FILENAME).write_text(dump_index(rows, reg.info))


@pytest.fixture
def reg(tmp_path):
    return build(tmp_path / "reg", {
        ("png", "png"): dict(version="1.0", extensions=["png"]),
        ("png", "png-apng"): dict(version="1.0", extensions=["png"], extends=["png"]),
        ("gif", "gif"): dict(version="1.0"),
    })


# --- the file

def test_a_lock_survives_being_written_and_read():
    lock = Lock(
        registries={"": "https://github.com/fandango-fuzzer/fanbase/tree/v1", "acme": "https://example.org/acme"},
        specs=[
            LockedSpec("", "png", "png", "1.0", SHA, True),
            LockedSpec("acme", "png", "png-strict", None, SHA, False),
        ],
    )
    back = load_lock_from_text(dump_lock(lock))
    assert back.registries == lock.registries and back.specs == lock.specs


def load_lock_from_text(text, tmp=[]):
    import pathlib
    import tempfile

    path = pathlib.Path(tempfile.mkdtemp()) / "fanbase.lock"
    path.write_text(text)
    return load_lock(path)


def test_the_file_says_what_it_is_and_names_the_default_registry_fanbase():
    text = dump_lock(Lock(registries={"": "u"}, specs=[LockedSpec("", "png", "png", "1.0", SHA, True)]))
    assert text.startswith("# generated by `fanbase lock`")
    data = yaml.safe_load(text)
    assert data["schema"] == 1 and data["registries"] == {"fanbase": "u"}
    assert data["specs"] == [{"spec": "png/png", "registry": "fanbase", "version": "1.0", "sha256": SHA, "requested": True}]


@pytest.mark.parametrize("change, complaint", [
    ({"schema": 2}, "upgrade fanbase"),
    ({"schema": "x"}, "upgrade fanbase"),
    ({"registries": ["u"]}, "registries has to map"),
    ({"specs": [5]}, "is not a spec"),
    ({"specs": [{"spec": "png", "sha256": SHA}]}, "format/kind"),
    ({"specs": [{"spec": "../x/y", "sha256": SHA}]}, "format/kind"),
    ({"specs": [{"spec": "png/png", "sha256": "nothex"}]}, "64 hex digits"),
    ({"specs": [{"spec": "png/png", "sha256": SHA, "registry": "acme"}]}, "not one of the registries listed"),
    ({"specs": [{"spec": "png/png", "sha256": SHA, "version": 1.0}]}, "version has to be text"),
])
def test_a_lock_that_is_not_valid_is_refused(change, complaint, tmp_path):
    data = {"schema": 1, "registries": {"fanbase": "u"}, "specs": []} | change
    path = tmp_path / "bad.lock"
    path.write_text(yaml.safe_dump(data))
    with pytest.raises(RegistryError, match=complaint):
        load_lock(path)


def test_a_missing_lock_says_how_to_make_one(tmp_path):
    with pytest.raises(RegistryError, match="fanbase lock SPEC"):
        load_lock(tmp_path / "nope.lock")


# --- fanbase lock

def test_lock_records_the_specs_and_what_they_extend(capsys, reg, project):
    code, out, _ = run(capsys, "--registry", str(reg), "lock", "png-apng")
    assert code == 0 and "locked 2 specs in fanbase.lock" in out
    lock = load_lock(project / "fanbase.lock")
    assert [(str(s), s.version, s.requested) for s in lock.specs] == [("png/png", "1.0", False), ("png/png-apng", "1.0", True)]
    index = yaml.safe_load((reg / INDEX_FILENAME).read_text())
    shas = {row["kind"]: row["sha256"] for row in index["specs"]}
    assert all(s.sha256 == shas[s.kind] for s in lock.specs)
    assert lock.registries == {"": str(reg)}


def test_lock_with_no_names_refreshes_what_was_asked_for(capsys, reg, project):
    run(capsys, "--registry", str(reg), "lock", "png-apng")
    republish(reg, "png", "<start> ::= 'png 2'\n", version="1.1")
    code, out, _ = run(capsys, "--registry", str(reg), "lock")
    assert code == 0 and "changed  png/png: 1.0" in out and "-> 1.1" in out
    assert load_lock(project / "fanbase.lock").find("", "png", "png").version == "1.1"
    assert [str(s) for s in load_lock(project / "fanbase.lock").requested] == ["png/png-apng"]


def test_lock_needs_something_to_lock(capsys, reg, project):
    code, _, err = run(capsys, "--registry", str(reg), "lock")
    assert code == 2 and "name the specs to lock" in err


def test_lock_check_is_for_ci(capsys, reg, project):
    run(capsys, "--registry", str(reg), "lock", "png-apng")
    code, out, _ = run(capsys, "--registry", str(reg), "lock", "--check")
    assert code == 0 and "up to date" in out
    republish(reg, "png-apng", "<start> ::= 'new'\n", version="1.1")
    code, out, _ = run(capsys, "--registry", str(reg), "lock", "--check")
    assert code == 1 and "out of date" in out and "changed  png/png-apng" in out
    assert load_lock(project / "fanbase.lock").find("", "png", "png-apng").version == "1.0"  # --check writes nothing


def test_lock_check_without_a_lock(capsys, reg, project):
    code, _, err = run(capsys, "--registry", str(reg), "lock", "png", "--check")
    assert code == 2 and "does not exist" in err


def test_lock_warns_when_the_registry_changes_over_time(capsys, reg, project):
    _, _, err = run(capsys, "--registry", str(reg), "lock", "png")
    assert "changes over time" in err and "tree/<tag>" in err


@pytest.mark.parametrize("url, official, moving", [
    ("https://github.com/fandango-fuzzer/fanbase", True, True),
    ("https://github.com/fandango-fuzzer/fanbase.git", True, True),
    ("https://github.com/Fandango-Fuzzer/Fanbase/tree/main", True, True),
    ("https://github.com/fandango-fuzzer/fanbase/tree/v2026.10.14", True, False),
    ("https://github.com/fandango-fuzzer/fanbase/tree/9fceb02d0ae598e95dc970b74767f19372d7f9ef", True, False),
    ("https://github.com/someone/fanbase", False, True),
    ("https://github.com/fandango-fuzzer/fanbase-cli", False, True),
    ("http://github.com/fandango-fuzzer/fanbase", False, True),
    ("https://example.org/fanbase", False, True),
    ("/home/me/fanbase", False, True),
])
def test_which_urls_are_the_public_registry_and_which_ones_move(url, official, moving):
    assert is_official(url) is official and moves(url) is moving


# --- fanbase install --locked

def test_locked_installs_exactly_what_the_lock_says(capsys, reg, project, root):
    run(capsys, "--registry", str(reg), "lock", "png-apng")
    code, out, _ = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 0 and "2 specs from fanbase.lock: 2 installed" in out
    assert [str(d) for d in all_installed(root)] == ["png/png", "png/png-apng"]


def test_locked_installs_nothing_if_a_registry_has_moved_on(capsys, reg, project, root):
    run(capsys, "--registry", str(reg), "lock", "png-apng")
    republish(reg, "png", "<start> ::= 'png 2'\n", version="1.1")
    code, _, err = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 2
    assert "no longer match fanbase.lock" in err
    assert "png/png was locked at 1.0" in err and "the registry now has 1.1" in err
    assert "fanbase lock" in err
    assert all_installed(root) == []  # not even png-apng, which is unchanged


def test_locked_puts_back_a_spec_that_was_changed_locally(capsys, reg, project, root):
    run(capsys, "--registry", str(reg), "lock", "png")
    run(capsys, "--registry", str(reg), "install", "--locked")
    spec_path(root, "png", "png").write_text("# edited by hand\n")
    code, out, _ = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 0 and "updated png/png" in out
    assert spec_path(root, "png", "png").read_text() == "<start> ::= 'png'\n"


def test_locked_goes_into_a_directory_of_the_projects_own(capsys, reg, project, tmp_path):
    run(capsys, "--registry", str(reg), "lock", "png")
    code, _, _ = run(capsys, "--registry", str(reg), "install", "--locked", "--into", str(project / ".fanbase"))
    assert code == 0 and (project / ".fanbase" / "png" / "png.fan").is_file()


def test_locked_takes_no_names_and_needs_a_lock(capsys, reg, project):
    assert run(capsys, "--registry", str(reg), "install", "--locked", "png")[0] == 2
    code, _, err = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 2 and "no fanbase.lock here" in err


def test_a_lock_can_be_named(capsys, reg, project, root):
    run(capsys, "--registry", str(reg), "lock", "gif", "--lockfile", "other.lock")
    assert not (project / "fanbase.lock").exists()
    code, out, _ = run(capsys, "--registry", str(reg), "install", "--locked", "--lockfile", "other.lock")
    assert code == 0 and "1 specs from other.lock" in out


def test_a_spec_that_left_the_registry_is_a_problem_too(capsys, reg, project, root):
    import shutil

    run(capsys, "--registry", str(reg), "lock", "gif", "png")
    shutil.rmtree(reg / "specs" / "gif")
    rows, _, _ = reindex(Registry(reg))
    (reg / INDEX_FILENAME).write_text(dump_index(rows))
    code, _, err = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 2 and "gif/gif: unknown format" in err
    assert all_installed(root) == []


# --- registries the user added

@pytest.fixture
def acme(tmp_path):
    return build(tmp_path / "acme", {("png", "png-strict"): dict(version="1.0")}, name="acme")


def test_a_lock_with_a_registry_you_added(capsys, reg, acme, project, root):
    run(capsys, "--registry", str(reg), "registry", "add", str(acme), "--trust")
    run(capsys, "--registry", str(reg), "lock", "png", "acme:png-strict")
    lock = load_lock(project / "fanbase.lock")
    assert lock.registries["acme"] == str(acme.resolve()) and lock.find("acme", "png", "png-strict").requested
    code, out, _ = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 0 and "2 specs" in out
    assert spec_path(root, "png", "png-strict", "acme").is_file()


def test_a_lock_that_uses_a_registry_you_have_not_added(capsys, reg, acme, project, root):
    run(capsys, "--registry", str(reg), "registry", "add", str(acme), "--trust")
    run(capsys, "--registry", str(reg), "lock", "acme:png-strict")
    run(capsys, "--registry", str(reg), "registry", "remove", "acme")
    code, _, err = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 2 and "which you have not added" in err and "registry add" in err and "--name acme" in err
    assert all_installed(root) == []


def test_a_registry_you_added_elsewhere_than_the_lock_says_is_pointed_out(capsys, reg, acme, project, tmp_path):
    run(capsys, "--registry", str(reg), "registry", "add", str(acme), "--trust")
    run(capsys, "--registry", str(reg), "lock", "acme:png-strict")
    path = project / "fanbase.lock"
    path.write_text(path.read_text().replace(str(acme.resolve()), "https://elsewhere.example/acme"))
    code, _, err = run(capsys, "--registry", str(reg), "install", "--locked")
    assert code == 0 and "you added acme as" in err and "elsewhere.example" in err  # the hashes still hold


# --- which default registry a lock reads

def test_a_lock_naming_some_other_default_registry_is_not_followed(tmp_path, monkeypatch, reg):
    monkeypatch.delenv("FANBASE_REGISTRY", raising=False)
    monkeypatch.chdir(reg)  # a checkout is found here, so nothing is fetched
    from fanbase.locking import locked_registry

    lock = Lock(registries={"": "https://example.org/somewhere"}, specs=[])
    with pytest.raises(RegistryError, match="pass --registry https://example.org/somewhere"):
        locked_registry(Context(), lock, "")
    assert locked_registry(Context(explicit=str(reg)), lock, "").root == reg  # unless the user says so


def test_a_lock_that_names_the_public_registry_reads_it_from_there(monkeypatch):
    monkeypatch.delenv("FANBASE_REGISTRY", raising=False)
    lock = Lock(registries={"": "https://github.com/fandango-fuzzer/fanbase/tree/v1"})
    ctx = lock_context(lock, None)
    assert ctx._explicit == "https://github.com/fandango-fuzzer/fanbase/tree/v1"  # opened only when needed


@pytest.mark.parametrize("given", ["reg", "env"])
def test_what_the_user_chose_comes_before_the_lock(monkeypatch, reg, given):
    lock = Lock(registries={"": "https://github.com/fandango-fuzzer/fanbase/tree/v1"})
    if given == "env":
        monkeypatch.setenv("FANBASE_REGISTRY", str(reg))
        ctx = lock_context(lock, None)
        assert ctx._explicit is None
    else:
        ctx = lock_context(lock, Registry(reg))
        assert ctx.default.root == reg


# --- fandango -F, which is ensure()

def lock_for(capsys, reg, project, *refs):
    assert run(capsys, "--registry", str(reg), "lock", *refs)[0] == 0


def test_ensure_holds_a_run_to_the_lock(capsys, reg, project, root):
    lock_for(capsys, reg, project, "png-apng")
    assert ensure("png-apng", Registry(reg), root).status == "installed"  # ./fanbase.lock is found
    republish(reg, "png-apng", "<start> ::= 'moved on'\n", version="1.1")
    with pytest.raises(RegistryError, match="png/png-apng was locked at 1.0.*now has 1.1.*fanbase lock"):
        ensure("png-apng", Registry(reg), root)
    assert spec_path(root, "png", "png-apng").read_text() == "<start> ::= 'png-apng'\n"  # still the locked one


def test_ensure_checks_what_a_spec_extends_against_the_lock_too(capsys, reg, project, root):
    lock_for(capsys, reg, project, "png-apng")
    republish(reg, "png", "<start> ::= 'png moved on'\n", version="1.1")
    with pytest.raises(RegistryError, match="png/png was locked"):
        ensure("png-apng", Registry(reg), root)
    assert all_installed(root) == []  # nothing was installed on the way


def test_ensure_without_a_lock_takes_what_the_registry_has(capsys, reg, project, root):
    ensure("png", Registry(reg), root)
    republish(reg, "png", "<start> ::= 'png 2'\n", version="1.1")
    assert ensure("png", Registry(reg), root).status == "updated"


def test_ensure_notes_a_spec_the_lock_does_not_have(capsys, reg, project, root, caplog):
    lock_for(capsys, reg, project, "png")
    with caplog.at_level(logging.WARNING, logger="fanbase"):
        done = ensure("gif", Registry(reg), root)
    assert done.status == "installed" and "gif/gif is not in the lock" in caplog.text


def test_ensure_takes_the_lock_named_in_the_environment(capsys, reg, project, root, monkeypatch, tmp_path):
    lock_for(capsys, reg, project, "png")
    (project / "fanbase.lock").rename(tmp_path / "elsewhere.lock")
    republish(reg, "png", "<start> ::= 'png 2'\n", version="1.1")
    assert ensure("png", Registry(reg), root).status == "installed"  # no lock here: anything goes
    monkeypatch.setenv("FANBASE_LOCK", str(tmp_path / "elsewhere.lock"))
    with pytest.raises(RegistryError, match="was locked"):
        ensure("png", Registry(reg), root, )


def test_ensure_offline_uses_the_installed_copy_only_if_it_is_the_locked_one(capsys, reg, project, root, monkeypatch):
    lock_for(capsys, reg, project, "png")
    ensure("png", Registry(reg), root)
    monkeypatch.setenv("FANBASE_REGISTRY", "http://127.0.0.1:9")
    assert ensure("png", root=root).status == "offline"
    spec_path(root, "png", "png").write_text("# edited\n")
    meta = spec_path(root, "png", "png").with_suffix(".yml")
    data = yaml.safe_load(meta.read_text())
    data["sha256"] = "00" * 32  # the installed copy is not what was locked
    meta.write_text(yaml.safe_dump(data))
    with pytest.raises(RegistryError, match="not the one fanbase.lock says"):
        ensure("png", root=root)
