"""fanbase.lock: exactly which specs a project uses, so a run can be repeated.

    schema: 1
    registries:
      fanbase: https://github.com/fandango-fuzzer/fanbase/tree/v2026.10.14
      acme: https://github.com/acme/fuzz-specs
    specs:
    - spec: png/png
      registry: fanbase
      version: '1.0'
      sha256: 3b1f...
      requested: true          # named by the user; the others are what those extend

`fanbase lock` writes it, `fanbase install --locked` installs exactly what it says and
refuses anything the registries now have differently, and `fandango -F` in a directory
with a lock (or with $FANBASE_LOCK set) does the same for the specs in it.

A lock holds hashes, not copies. To get a spec again once it has changed in the registry,
the registry has to be read at a release where it was still as locked, which is why the
registry's URL is in the lock: lock against a tag (`.../tree/<tag>`), not against `main`.
"""

from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from fanbase.registry import DEFAULT_REGISTRY_NAME, SAFE_NAME, RegistryError

LOCK_FILENAME = "fanbase.lock"
ENV_LOCK = "FANBASE_LOCK"
LOCK_SCHEMA = 1

GENERATED_COMMENT = (
    "# generated by `fanbase lock`; commit it.\n"
    "# `fanbase install --locked` installs exactly this.\n"
)

_SHA256 = re.compile(r"[0-9a-f]{64}")


@dataclass(frozen=True)
class LockedSpec:
    registry: str  # "" is the default registry
    format: str
    kind: str
    version: str | None
    sha256: str
    requested: bool = False

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.registry, self.format, self.kind)

    def __str__(self) -> str:
        spec = f"{self.format}/{self.kind}"
        return f"{self.registry}:{spec}" if self.registry else spec


@dataclass
class Lock:
    registries: dict[str, str] = field(default_factory=dict)  # name -> where it was read from
    specs: list[LockedSpec] = field(default_factory=list)

    def find(self, registry: str, fmt: str, kind: str) -> LockedSpec | None:
        return next((spec for spec in self.specs if spec.key == (registry, fmt, kind)), None)

    @property
    def requested(self) -> list[LockedSpec]:
        return [spec for spec in self.specs if spec.requested]


def lock_path(explicit: str | os.PathLike | None = None) -> Path | None:
    """The lock to use: the one named, else $FANBASE_LOCK, else ./fanbase.lock if there is one."""
    if explicit:
        return Path(explicit)
    if env := os.environ.get(ENV_LOCK):
        return Path(env)
    here = Path(LOCK_FILENAME)  # relative, so messages say `fanbase.lock` and not where that is
    return here if here.is_file() else None


def load_lock(path: Path) -> Lock:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        raise RegistryError(f"{path} does not exist; `fanbase lock SPEC...` makes it") from None
    except yaml.YAMLError as exc:
        raise RegistryError(f"{path}: invalid YAML: {exc}") from None
    if not isinstance(data, dict):
        raise RegistryError(f"{path}: expected a mapping at the top level")
    schema = data.get("schema", LOCK_SCHEMA)
    if not isinstance(schema, int) or isinstance(schema, bool) or schema > LOCK_SCHEMA:
        raise RegistryError(f"{path} uses schema {schema!r}; upgrade fanbase to read it")

    lock = Lock()
    registries = data.get("registries") or {}
    if not isinstance(registries, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in registries.items()):
        raise RegistryError(f"{path}: registries has to map names to where they were read from")
    lock.registries = {("" if name == DEFAULT_REGISTRY_NAME else name): url for name, url in registries.items()}

    for item in data.get("specs") or []:
        where = f"{path}: {item!r}"
        if not isinstance(item, dict):
            raise RegistryError(f"{where} is not a spec")
        spec = item.get("spec")
        fmt, _, kind = spec.partition("/") if isinstance(spec, str) else ("", "", "")
        registry = item.get("registry", DEFAULT_REGISTRY_NAME)
        registry = "" if registry == DEFAULT_REGISTRY_NAME else registry
        sha, version = item.get("sha256"), item.get("version")
        if not (SAFE_NAME.fullmatch(fmt) and SAFE_NAME.fullmatch(kind)):
            raise RegistryError(f"{where}: spec has to be format/kind")
        if not isinstance(registry, str) or (registry and registry not in lock.registries):
            raise RegistryError(f"{where}: registry is not one of the registries listed")
        if not (isinstance(sha, str) and _SHA256.fullmatch(sha)):
            raise RegistryError(f"{where}: sha256 has to be 64 hex digits")
        if version is not None and not isinstance(version, str):
            raise RegistryError(f"{where}: version has to be text")
        lock.specs.append(LockedSpec(registry, fmt, kind, version, sha, bool(item.get("requested", False))))
    return lock


def dump_lock(lock: Lock) -> str:
    def name(registry: str) -> str:
        return registry or DEFAULT_REGISTRY_NAME

    data = {
        "schema": LOCK_SCHEMA,
        "registries": {name(r): url for r, url in sorted(lock.registries.items(), key=lambda kv: name(kv[0]))},
        "specs": [
            {
                "spec": f"{spec.format}/{spec.kind}",
                "registry": name(spec.registry),
                **({"version": spec.version} if spec.version is not None else {}),
                "sha256": spec.sha256,
                **({"requested": True} if spec.requested else {}),
            }
            for spec in lock.specs
        ],
    }
    return GENERATED_COMMENT + yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def save_lock(lock: Lock, path: Path) -> None:
    text = dump_lock(lock)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
