"""metadata.yml for each spec, and index.yml for the registry as a whole.

`fanbase reindex` keeps both in step with the `.fan` files. A person writes the
description (and may adjust `fandango`); everything else is filled in from the spec and
the installed package. index.yml is the same data in one file, so a client can browse a
registry and fetch a single spec without cloning it. Neither file should drift from the
specs, which is why they are generated rather than maintained by hand.
"""

from __future__ import annotations

import hashlib
import re
import sys
from dataclasses import replace

import yaml
from packaging.version import InvalidVersion, Version

from fanbase import __version__
from fanbase.deps import check_registry_dependencies
from fanbase.registry import (
    METADATA_FILENAME,
    Entry,
    Registry,
    RegistryBase,
    RegistryError,
    check_registry_info,
    is_safe_name,
    is_safe_path,
)

INDEX_FILENAME = "index.yml"

# The layout of index.yml. A client that meets a higher number than it knows refuses, and
# says to upgrade, rather than guess. An index without the key is schema 1.
SCHEMA_VERSION = 2

GENERATED_COMMENT = "# generated by `fanbase reindex`; do not edit by hand\n"

# Fandango release the specs are written against. Edit a spec's metadata.yml to override it.
DEFAULT_FANDANGO = ">=1.3"

# Keys in the order they are written; any others a person adds follow, untouched.
KEY_ORDER = ("format", "kind", "description", "fanbase", "fandango", "requires")

# Keys a person may add, all optional. They come right after KEY_ORDER, in this order, and
# `reindex` refuses a value of the wrong shape. Everything else a person adds is kept as is.
#   authors       who wrote it: names, or {name, orcid}
#   license       SPDX identifier of the spec's license (Apache-2.0, MIT, ...)
#   source        what it was made from: a URL, or a few words
#   extends       specs it builds on, as refs (`png`, `png/png-apng`)
#   derived_from  the spec it was forked from, as a ref
#   status        draft, stable or deprecated
#   doi           the DOI of an archived copy (Zenodo)
OPTIONAL_KEYS = ("authors", "license", "source", "extends", "derived_from", "status", "doi")
STATUSES = ("draft", "stable", "deprecated")

_ORCID = re.compile(r"\d{4}-\d{4}-\d{4}-\d{3}[\dX]")
_DOI = re.compile(r"10\.\d{4,9}/\S+")

_FROM_IMPORT = re.compile(r"^[ \t]*from[ \t]+([A-Za-z_]\w*)[\w.]*[ \t]+import\b", re.MULTILINE)
_IMPORT = re.compile(r"^[ \t]*import[ \t]+([^#\n]+)", re.MULTILINE)


def detect_requires(source: str) -> list[str]:
    """Third-party packages a spec imports, by import name.

    A `.fan` file is not valid Python, so imports are picked out line by line rather
    than parsed. The standard library and Fandango itself don't count.
    """
    names = set(_FROM_IMPORT.findall(source))
    for clause in _IMPORT.findall(source):
        for part in clause.split(","):
            words = part.split()
            if words:
                names.add(words[0].split(".")[0])
    ignore = sys.stdlib_module_names | {"fandango"}
    return sorted(n for n in names if n.isidentifier() and n not in ignore)


def refresh_metadata(entry: Entry, source: str) -> dict:
    """The entry's metadata with the derived fields brought up to date."""
    meta = dict(entry.meta)
    meta.update(format=entry.format, kind=entry.kind, fanbase=__version__,
                requires=detect_requires(source))
    meta.setdefault("description", "")
    meta.setdefault("fandango", DEFAULT_FANDANGO)
    ordered = {k: meta[k] for k in KEY_ORDER}
    ordered.update((k, meta[k]) for k in OPTIONAL_KEYS if k in meta)
    ordered.update((k, v) for k, v in meta.items() if k not in ordered)
    return ordered


def _is_text(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def check_metadata(meta: dict) -> list[str]:
    """What is wrong with the optional keys of a spec's metadata, one line each."""
    problems = []
    if "version" in meta:
        try:
            Version(meta["version"])
        except (InvalidVersion, TypeError):
            problems.append(f"version: {meta['version']!r} is not a version number; write it in quotes, like '1.0'")
    for key in ("license", "source", "derived_from"):
        if key in meta and not _is_text(meta[key]):
            problems.append(f"{key}: expected text")
    if "status" in meta and meta["status"] not in STATUSES:
        problems.append(f"status: {meta['status']!r} is not one of {', '.join(STATUSES)}")
    if "doi" in meta and not (isinstance(meta["doi"], str) and _DOI.fullmatch(meta["doi"])):
        problems.append(f"doi: {meta['doi']!r} is not a DOI like 10.5281/zenodo.1234567")
    if "extends" in meta:
        refs = meta["extends"]
        if not isinstance(refs, list) or not all(_is_text(ref) for ref in refs):
            problems.append("extends: expected a list of spec names")
    if "authors" in meta:
        authors = meta["authors"]
        if not isinstance(authors, list) or not authors:
            problems.append("authors: expected a list of names, or of {name, orcid}")
        else:
            for author in authors:
                name = author.get("name") if isinstance(author, dict) else author
                if not _is_text(name):
                    problems.append(f"authors: {author!r} has no name")
                elif isinstance(author, dict) and "orcid" in author and not (
                    isinstance(author["orcid"], str) and _ORCID.fullmatch(author["orcid"])
                ):
                    problems.append(
                        f"authors: {name}: orcid {author['orcid']!r} is not like 0000-0002-1825-0097"
                    )
    return problems


def dump_metadata(meta: dict) -> str:
    return yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)


class _Planned(RegistryBase):
    """The registry as it will be once reindexed: the specs with their refreshed metadata."""

    def __init__(self, registry: Registry, planned: list) -> None:
        self.info = registry.info
        self._entries = [replace(entry, meta=meta) for _, entry, _, meta in planned]

    def formats(self) -> list[str]:
        return sorted({e.format for e in self._entries})

    def kinds(self, fmt: str) -> list[Entry]:
        return sorted((e for e in self._entries if e.format == fmt), key=lambda e: e.kind)

    def read(self, entry: Entry) -> bytes:
        raise NotImplementedError


def reindex(registry: Registry, *, write: bool = True) -> tuple[list[dict], list[Entry], list[Entry]]:
    """Refresh every metadata.yml, then return the index rows.

    Returns (rows, changed, undescribed): the index, the entries whose metadata.yml was
    (or, with write=False, would be) rewritten, and the entries still missing a description.
    A change to the `fanbase` key alone, the version that last ran reindex, doesn't count
    when only checking.
    """
    rows: list[dict] = []
    changed: list[Entry] = []
    undescribed: list[Entry] = []

    planned = []
    problems = []
    for fmt in registry.formats():
        for entry in registry.kinds(fmt):
            raw = registry.read(entry)
            meta = refresh_metadata(entry, raw.decode("utf-8", errors="replace"))
            problems.extend(f"{entry}: {problem}" for problem in check_metadata(meta))
            planned.append((fmt, entry, raw, meta))
    check_registry_dependencies(_Planned(registry, planned), problems)
    if problems:
        # Nothing has been written yet: a registry is not left half refreshed.
        raise RegistryError("invalid metadata:\n  " + "\n  ".join(problems))

    for fmt, entry, raw, meta in planned:
        target = (registry.root / entry.path).with_name(METADATA_FILENAME)

        text = dump_metadata(meta)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if write:
            if current != text:
                target.write_text(text, encoding="utf-8")
                changed.append(entry)
        elif current is None or _without_stamp(current) != _without_stamp(text):
            changed.append(entry)
        if not meta["description"]:
            undescribed.append(entry)

        rows.append({"format": fmt, "kind": entry.kind, "path": entry.path,
                     "sha256": hashlib.sha256(raw).hexdigest(),
                     **{k: v for k, v in meta.items() if k not in ("format", "kind")}})
    return rows, changed, undescribed


def _without_stamp(text: str) -> dict:
    data = yaml.safe_load(text) or {}
    data.pop("fanbase", None)
    return data


def dump_index(rows: list[dict], info: dict | None = None) -> str:
    """index.yml: the schema, the registry's own details if it has any, then every spec."""
    index: dict = {"schema": SCHEMA_VERSION}
    if info:
        index["registry"] = info
    index["specs"] = rows
    return GENERATED_COMMENT + yaml.safe_dump(index, sort_keys=False, allow_unicode=True)


def parse_index(text: str) -> list[Entry]:
    return parse_index_full(text)[0]


def parse_index_full(text: str) -> tuple[list[Entry], dict]:
    """The specs of an index.yml, and the details of the registry it describes.

    The index comes from a registry we may not control, and what it names is used to build
    URLs and file names, so a format, a kind or a path that could point outside the
    registry (or the install directory) is refused.
    """
    malformed = RegistryError(f"{INDEX_FILENAME} is malformed; the registry needs `fanbase reindex`")
    try:
        data = yaml.safe_load(text) or {}
        schema = data.get("schema", 1)
        if not isinstance(schema, int) or isinstance(schema, bool):
            raise malformed
        if schema > SCHEMA_VERSION:
            raise RegistryError(
                f"{INDEX_FILENAME} uses schema {schema}, and this fanbase understands up to "
                f"{SCHEMA_VERSION}; upgrade it with `pip install --upgrade fanbase`"
            )
        info = check_registry_info(data.get("registry"), f"{INDEX_FILENAME} registry")
        entries = []
        for row in data.get("specs", []):
            entry = Entry(row["format"], row["kind"], row["path"], sha256=row.get("sha256", ""),
                          meta={k: v for k, v in row.items()
                                if k not in ("format", "kind", "path", "sha256")})
            if not (is_safe_name(entry.format) and is_safe_name(entry.kind)
                    and is_safe_path(entry.path) and isinstance(entry.sha256, str)):
                raise RegistryError(
                    f"{INDEX_FILENAME} names a spec that is not safe to use "
                    f"({entry.format!r}, {entry.kind!r}, {entry.path!r})"
                )
            entries.append(entry)
        return entries, info
    except (yaml.YAMLError, AttributeError, KeyError, TypeError):
        raise malformed from None


def index_view(text: str) -> tuple[int, dict, list[dict]]:
    """An index's schema, registry details and rows, without the `fanbase` stamp, for
    comparing two indexes."""
    data = yaml.safe_load(text) or {}
    rows = [{k: v for k, v in row.items() if k != "fanbase"} for row in data.get("specs", [])]
    return data.get("schema", 1), data.get("registry") or {}, rows


def index_is_stale(registry: Registry, rows: list[dict]) -> bool:
    """Does the registry's index.yml differ from what `reindex` would write now?

    The index repeats the `fanbase` stamp, which says nothing about the specs, so it is
    left out of the comparison.
    """
    index_file = registry.root / INDEX_FILENAME
    if not index_file.is_file():
        return True
    fresh = dump_index(rows, registry.info)
    current = index_file.read_text(encoding="utf-8")
    return current != fresh and index_view(current) != index_view(fresh)
