"""metadata.yml for each spec, and index.yml for the registry as a whole.

`fanbase reindex` keeps both in step with the `.fan` files. A person writes the
description (and may adjust `fandango`); everything else is filled in from the spec and
the installed package. index.yml is the same data in one file, so a client can browse a
registry and fetch a single spec without cloning it. Neither file should drift from the
specs, which is why they are generated rather than maintained by hand.
"""

from __future__ import annotations

import hashlib
import re
import sys

import yaml

from fanbase import __version__
from fanbase.registry import METADATA_FILENAME, Entry, Registry, RegistryError

INDEX_FILENAME = "index.yml"
GENERATED_COMMENT = "# generated by `fanbase reindex`; do not edit by hand\n"

# Fandango release the specs are written against. Edit a spec's metadata.yml to override it.
DEFAULT_FANDANGO = ">=1.3"

# Keys in the order they are written; any others a person adds follow, untouched.
KEY_ORDER = ("format", "kind", "description", "fanbase", "fandango", "requires")

_FROM_IMPORT = re.compile(r"^[ \t]*from[ \t]+([A-Za-z_]\w*)[\w.]*[ \t]+import\b", re.MULTILINE)
_IMPORT = re.compile(r"^[ \t]*import[ \t]+([^#\n]+)", re.MULTILINE)


def detect_requires(source: str) -> list[str]:
    """Third-party packages a spec imports, by import name.

    A `.fan` file is not valid Python, so imports are picked out line by line rather
    than parsed. The standard library and Fandango itself don't count.
    """
    names = set(_FROM_IMPORT.findall(source))
    for clause in _IMPORT.findall(source):
        for part in clause.split(","):
            words = part.split()
            if words:
                names.add(words[0].split(".")[0])
    ignore = sys.stdlib_module_names | {"fandango"}
    return sorted(n for n in names if n.isidentifier() and n not in ignore)


def refresh_metadata(entry: Entry, source: str) -> dict:
    """The entry's metadata with the derived fields brought up to date."""
    meta = dict(entry.meta)
    meta.update(format=entry.format, kind=entry.kind, fanbase=__version__,
                requires=detect_requires(source))
    meta.setdefault("description", "")
    meta.setdefault("fandango", DEFAULT_FANDANGO)
    ordered = {k: meta[k] for k in KEY_ORDER}
    ordered.update((k, v) for k, v in meta.items() if k not in ordered)
    return ordered


def dump_metadata(meta: dict) -> str:
    return yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)


def reindex(registry: Registry, *, write: bool = True) -> tuple[list[dict], list[Entry], list[Entry]]:
    """Refresh every metadata.yml, then return the index rows.

    Returns (rows, changed, undescribed): the index, the entries whose metadata.yml was
    (or, with write=False, would be) rewritten, and the entries still missing a description.
    A change to the `fanbase` key alone, the version that last ran reindex, doesn't count
    when only checking.
    """
    rows: list[dict] = []
    changed: list[Entry] = []
    undescribed: list[Entry] = []

    for fmt in registry.formats():
        for entry in registry.kinds(fmt):
            raw = registry.read(entry)
            meta = refresh_metadata(entry, raw.decode("utf-8", errors="replace"))
            target = (registry.root / entry.path).with_name(METADATA_FILENAME)

            text = dump_metadata(meta)
            current = target.read_text(encoding="utf-8") if target.exists() else None
            if write:
                if current != text:
                    target.write_text(text, encoding="utf-8")
                    changed.append(entry)
            elif current is None or _without_stamp(current) != _without_stamp(text):
                changed.append(entry)
            if not meta["description"]:
                undescribed.append(entry)

            rows.append({"format": fmt, "kind": entry.kind, "path": entry.path,
                         "sha256": hashlib.sha256(raw).hexdigest(),
                         **{k: v for k, v in meta.items() if k not in ("format", "kind")}})
    return rows, changed, undescribed


def _without_stamp(text: str) -> dict:
    data = yaml.safe_load(text) or {}
    data.pop("fanbase", None)
    return data


def dump_index(rows: list[dict]) -> str:
    return GENERATED_COMMENT + yaml.safe_dump({"specs": rows}, sort_keys=False, allow_unicode=True)


def parse_index(text: str) -> list[Entry]:
    try:
        rows = (yaml.safe_load(text) or {}).get("specs", [])
        return [
            Entry(row["format"], row["kind"], row["path"], sha256=row.get("sha256", ""),
                  meta={k: v for k, v in row.items()
                        if k not in ("format", "kind", "path", "sha256")})
            for row in rows
        ]
    except (yaml.YAMLError, AttributeError, KeyError, TypeError):
        raise RegistryError(f"{INDEX_FILENAME} is malformed; the registry needs `fanbase reindex`") from None
